### ISSUE TITLE
ArrayIndexOutOfBoundsException when decompiling certain files from Skytils

### ISSUE THREAD

**Issue by sqlongithub** [ilumn/fractureiser-detector#2]
Sometimes when decompiling files from the Skytils mod (version 1.6.0), the decompiler throws an ArrayIndexOutOfBoundsException 

I think this is an issue with Procyon, but I thought I might as well let you know incase you can do anything about it.

Examples:
https://pastebin.com/raw/REGeNxYU
https://pastebin.com/raw/pH70ahwA
https://pastebin.com/raw/eHnisMCD

**Comment by ilumn** [comment]
Yeah, this is up to Procyon to fix. I will replace Procyon with another de-compiler like Fernflower if i can find a safe pre-compiled binary for the scanner to use.
